PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS ACHAT_JOURNALIERE;
DROP TABLE IF EXISTS STOCK;
DROP TABLE IF EXISTS OBJECTIF_MENSUEL;
DROP TABLE IF EXISTS VENTE_DSM_AU_POS;
DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS POS;
DROP TABLE IF EXISTS DSM;
DROP TABLE IF EXISTS DA;
DROP TABLE IF EXISTS CENTRE;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS ZONE;

CREATE TABLE ZONE (
    ID_ZONE TEXT PRIMARY KEY NOT NULL,
    NOM_ZONE TEXT NOT NULL,
    REGION TEXT NOT NULL
);

CREATE TABLE CENTRE (
    ID_CENTRE TEXT PRIMARY KEY NOT NULL,
    NOM_CENTRE TEXT NOT NULL,
    REGION TEXT NOT NULL
);

CREATE TABLE ROLE (
    ID_ROLE TEXT PRIMARY KEY NOT NULL,
    LIBELLE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE DA (
    ID_DA TEXT PRIMARY KEY NOT NULL,
    ID_ZONE TEXT NOT NULL,
    ID_CENTRE TEXT NOT NULL,
    NOM_DA TEXT NOT NULL,
    RAISON_SOCIALE TEXT NOT NULL,
    STATUT TEXT NOT NULL,
    ADRESSE TEXT NOT NULL,
    CONTACT TEXT NOT NULL,
    DATE_ADHESION TEXT NOT NULL,
    FOREIGN KEY (ID_ZONE) REFERENCES ZONE(ID_ZONE),
    FOREIGN KEY (ID_CENTRE) REFERENCES CENTRE(ID_CENTRE)
);

CREATE TABLE DSM (
    ID_DSM TEXT PRIMARY KEY NOT NULL,
    ID_ZONE TEXT NOT NULL,
    ID_DA TEXT NOT NULL,
    NOM_DSM TEXT NOT NULL,
    RAISON_SOCIALE TEXT NOT NULL,
    ADRESSE TEXT NOT NULL,
    STATUT INTEGER NOT NULL CHECK (STATUT IN (0,1)),
    CONTACT TEXT NOT NULL,
    DATE_ADHESION TEXT NOT NULL,
    FOREIGN KEY (ID_ZONE) REFERENCES ZONE(ID_ZONE),
    FOREIGN KEY (ID_DA) REFERENCES DA(ID_DA)
);

CREATE TABLE POS (
    ID_POS TEXT PRIMARY KEY NOT NULL,
    ID_DSM TEXT NOT NULL,
    ID_ZONE TEXT NOT NULL,
    NOM_POS TEXT NOT NULL,
    RAISON_SOCIALE TEXT NOT NULL,
    ADRESSE TEXT NOT NULL,
    STATUT INTEGER NOT NULL CHECK (STATUT IN (0,1)),
    CONTACT TEXT NOT NULL,
    DATE_ADHESION TEXT NOT NULL,
    FOREIGN KEY (ID_DSM) REFERENCES DSM(ID_DSM),
    FOREIGN KEY (ID_ZONE) REFERENCES ZONE(ID_ZONE)
);

CREATE TABLE UTILISATEUR (
    ID_UTILISATEUR TEXT PRIMARY KEY NOT NULL,
    ID_ROLE TEXT NOT NULL,
    ID_ZONE TEXT NOT NULL,
    MATRICULE TEXT NOT NULL,
    NOM_COMPLET TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    TELEPHONE TEXT NOT NULL,
    MOT_DE_PASSE TEXT NOT NULL,
    STATUT INTEGER NOT NULL CHECK (STATUT IN (0,1)),
    ID_MANAGER TEXT NOT NULL,
    DATE_CONNEXION TEXT NOT NULL,
    DERNIERE_CONNEXION TEXT NOT NULL,
    FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID_ROLE),
    FOREIGN KEY (ID_ZONE) REFERENCES ZONE(ID_ZONE),
    FOREIGN KEY (ID_MANAGER) REFERENCES UTILISATEUR(ID_UTILISATEUR)
);

CREATE TABLE VENTE_DSM_AU_POS (
    ID_VENTE TEXT PRIMARY KEY NOT NULL,
    ID_DSM TEXT NOT NULL,
    ID_POS TEXT NOT NULL,
    DATE_VENTE TEXT NOT NULL,
    QUANTITE_VENDU REAL NOT NULL,
    MONTANT REAL NOT NULL,
    DATE_SAISIE TEXT NOT NULL,
    FOREIGN KEY (ID_DSM) REFERENCES DSM(ID_DSM),
    FOREIGN KEY (ID_POS) REFERENCES POS(ID_POS)
);

CREATE TABLE OBJECTIF_MENSUEL (
    ID_OBJECTIF TEXT PRIMARY KEY NOT NULL,
    ID_POS TEXT,
    ID_DA TEXT,
    ID_DSM TEXT,
    MOIS_ANNEE TEXT NOT NULL,
    MONTANT_OBJECTIF REAL NOT NULL,
    STATUT INTEGER NOT NULL CHECK (STATUT IN (0,1)),
    FOREIGN KEY (ID_POS) REFERENCES POS(ID_POS),
    FOREIGN KEY (ID_DA) REFERENCES DA(ID_DA),
    FOREIGN KEY (ID_DSM) REFERENCES DSM(ID_DSM)
);

CREATE TABLE STOCK (
    ID_STOCK TEXT PRIMARY KEY NOT NULL,
    ID_POS TEXT NOT NULL,
    ID_DA TEXT NOT NULL,
    ID_DSM TEXT NOT NULL,
    DATE_STOCK TEXT NOT NULL,
    QUANTITE_CREDIT REAL NOT NULL,
    STATUT INTEGER NOT NULL CHECK (STATUT IN (0,1)),
    DATE_SAISIR TEXT NOT NULL,
    FOREIGN KEY (ID_POS) REFERENCES POS(ID_POS),
    FOREIGN KEY (ID_DA) REFERENCES DA(ID_DA),
    FOREIGN KEY (ID_DSM) REFERENCES DSM(ID_DSM)
);

CREATE TABLE ACHAT_JOURNALIERE (
    ID_ACHAT TEXT PRIMARY KEY NOT NULL,
    ID_UTILISATEUR TEXT NOT NULL,
    ID_DSM TEXT,
    ID_DA TEXT,
    ID_POS TEXT,
    DATE_ACHAT TEXT NOT NULL,
    MONTANT_ACHAT REAL NOT NULL,
    DATE_SAISIE TEXT NOT NULL,
    FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
    FOREIGN KEY (ID_DSM) REFERENCES DSM(ID_DSM),
    FOREIGN KEY (ID_DA) REFERENCES DA(ID_DA),
    FOREIGN KEY (ID_POS) REFERENCES POS(ID_POS)
);

CREATE INDEX I_FK_UTILISATEUR_ROLE ON UTILISATEUR(ID_ROLE);
CREATE INDEX I_FK_UTILISATEUR_ZONE ON UTILISATEUR(ID_ZONE);
CREATE INDEX I_FK_POS_DSM ON POS(ID_DSM);
CREATE INDEX I_FK_POS_ZONE ON POS(ID_ZONE);
CREATE INDEX I_FK_VENTE_DSM_AU_POS_DSM ON VENTE_DSM_AU_POS(ID_DSM);
CREATE INDEX I_FK_VENTE_DSM_AU_POS_POS ON VENTE_DSM_AU_POS(ID_POS);
CREATE INDEX I_FK_OBJECTIF_MENSUEL_POS ON OBJECTIF_MENSUEL(ID_POS);
CREATE INDEX I_FK_OBJECTIF_MENSUEL_DA ON OBJECTIF_MENSUEL(ID_DA);
CREATE INDEX I_FK_OBJECTIF_MENSUEL_DSM ON OBJECTIF_MENSUEL(ID_DSM);
CREATE INDEX I_FK_STOCK_POS ON STOCK(ID_POS);
CREATE INDEX I_FK_STOCK_DA ON STOCK(ID_DA);
CREATE INDEX I_FK_STOCK_DSM ON STOCK(ID_DSM);
CREATE INDEX I_FK_ACHAT_JOURNALIERE_UTILISATEUR ON ACHAT_JOURNALIERE(ID_UTILISATEUR);
CREATE INDEX I_FK_ACHAT_JOURNALIERE_DSM ON ACHAT_JOURNALIERE(ID_DSM);
CREATE INDEX I_FK_ACHAT_JOURNALIERE_DA ON ACHAT_JOURNALIERE(ID_DA);
CREATE INDEX I_FK_ACHAT_JOURNALIERE_POS ON ACHAT_JOURNALIERE(ID_POS);
CREATE INDEX I_FK_DSM_ZONE ON DSM(ID_ZONE);
CREATE INDEX I_FK_DSM_DA ON DSM(ID_DA);
CREATE INDEX I_FK_DA_ZONE ON DA(ID_ZONE);
CREATE INDEX I_FK_DA_CENTRE ON DA(ID_CENTRE);
